### ISSUE TITLE
Circuit theme: Donkey Kong image corrupt

### ISSUE THREAD

**Issue by andresdelcampo** [RetroHursty69/es-theme-circuit#1]
This image is corrupt and is the only version uploaded. 
I hope you have any backups...?

https://github.com/RetroHursty69/es-theme-circuit/blob/master/donkeykong/_inc/system.png

If not, I guess you could consider removing the folder -it shows an empty slot in the UI and warnings in the console instead of adding it to the Collections circuit.

Thanks,
Andrés

**Comment by RetroHursty69** [comment]
Thanks for finding. It is now fixed.

**Comment by andresdelcampo** [comment]
Impressive! -your reaction speed, the fix, and in general all your work. 
I am loving it. Thanks!!!
